import { ScheduleShow, ScheduleResponse } from '../types/Schedule';

export const mockScheduleShows: ScheduleShow[] = [
  // Sunday
  {
    id: '8974',
    name: 'Compas sur FM',
    day: 0,
    day_str: 'Sunday',
    time: '360',
    time_str: '6:00a',
    length: 120,
    alternates: 0,
    hosts: 'Emmanuel Rene',
    multihosts: 0,
    producers: '101',
    url: '',
    email: '',
    description: "The show's goal is to present Compas Music to WMBR's audience.",
  },
  {
    id: '8982',
    name: 'Africa Kabisa',
    day: 0,
    day_str: 'Sunday',
    time: '960',
    time_str: '4:00p',
    length: 120,
    alternates: 0,
    hosts: 'Brutus leaderson',
    multihosts: 0,
    producers: '64',
    url: '',
    email: 'africa@wmbr.org',
    description: 'Africa Absolutely! Since 1992, Boston\'s African music radio show. Classic and contemporary African and Afro-Caribbean music. Soukous, rumba, zouk, kompa, makossa, mbalax, and more.',
  },
  // Sunday - Alternating shows
  {
    id: '8977',
    name: 'Sound and Fury',
    day: 0,
    day_str: 'Sunday',
    time: '600',
    time_str: '10:00a',
    length: 60,
    alternates: 1,
    hosts: 'David "The Central Cogitator" Goodman',
    multihosts: 0,
    producers: '40',
    url: '',
    email: '',
    description: 'Unconventional Wisdom Meets Dramatic Radio',
  },
  {
    id: '8976',
    name: 'Radio with a View',
    day: 0,
    day_str: 'Sunday',
    time: '600',
    time_str: '10:00a',
    length: 60,
    alternates: 2,
    hosts: 'Marc Stern',
    multihosts: 0,
    producers: '40,118',
    url: '',
    email: '',
    description: 'Economic democracy, human rights, and other idealistic visions of the world with interviews and music to get your mind and body in sync. Visit https://www.mixcloud.com/radiowithaview for podcasts of this show.',
  },
  // Monday
  {
    id: '9028',
    name: 'Nonstop Ecstatic Screaming',
    day: 1,
    day_str: 'Monday',
    time: '300',
    time_str: '5:00a',
    length: 120,
    alternates: 0,
    hosts: 'Thao',
    multihosts: 0,
    producers: '187',
    url: '',
    email: '',
    description: 'Two hours of sound designed to split your skull open, break your brain, and pop your funk. Bloopity bits and bobs, plinkety plonk, drone, skronk, assorted noise, a bumping beat here and there, etc.',
  },
  {
    id: '8992',
    name: 'Research & Development',
    day: 1,
    day_str: 'Monday',
    time: '840',
    time_str: '2:00p',
    length: 120,
    alternates: 0,
    hosts: 'Charlie Kohlhase',
    multihosts: 0,
    producers: '162',
    url: '',
    email: 'research',
    description: 'Forward-looking Jazz from from the 40\'s to the present. Occasional Birthday features. Classic Tenor Corner. Jazz Calendar Highlights.',
  },
  // Tuesday
  {
    id: '8998',
    name: 'If 6 Was 9',
    day: 2,
    day_str: 'Tuesday',
    time: '240',
    time_str: '4:00a',
    length: 180,
    alternates: 0,
    hosts: 'Rick Biskit Roth',
    multihosts: 0,
    producers: '1351',
    url: '',
    email: 'if6was9@wmbr.org',
    description: 'A morning wake-up that goes from jazz to punk with everything in between. Hendrix at the root branching into anything that has soul.',
  },
  {
    id: '9001',
    name: 'The Jazz Train',
    day: 2,
    day_str: 'Tuesday',
    time: '960',
    time_str: '4:00p',
    length: 90,
    alternates: 0,
    hosts: 'Jon Pollack',
    multihosts: 0,
    producers: '94',
    url: '',
    email: 'jazztrain',
    description: 'A weekly trip through the jazz legacy and related musical styles, generally featuring music recorded in past years on a particular calendar date.',
  },
  {
    id: '1003',
    name: 'Post-tentious',
    day: 2,
    day_str: 'Tuesday',
    time: '1290',
    time_str: '9:30p',
    length: 90,
    alternates: 0,
    hosts: 'Eda Lozada',
    multihosts: 0,
    producers: '',
    url: '',
    email: 'eda@wmbr.org',
    description: 'Post music for post people. We regularly play post-punk, post-rock, post-hardcore, and more.',
  },
];

export const mockScheduleResponse: ScheduleResponse = {
  shows: mockScheduleShows,
};
