export const CORE_COLORS = {
  WHITE: '#FFFFFF',
  BLACK: '#000000',
  GRAY_100: '#E0E0E0',
  GRAY_200: '#CCCCCC',
  // GRAY_300: '#BBBBBB',
  // GRAY_400: '#AAAAAA',
  // GRAY_500: '#999999',
  GRAY_600: '#888888',
  GRAY_700: '#555555',
  // GRAY_900: '#333333',
  GRAY_950: '#2a2a2a',
  GRAY_975: '#1a1a1a',
  RED_500: '#FF4444',
  // GREEN_500: '#00D17A',
  WMBR_GREEN: '#00843D',
  OVERLAY_WHITE_05: 'rgba(255, 255, 255, 0.05)',
  OVERLAY_WHITE_10: 'rgba(255, 255, 255, 0.1)',
} as const;

export const COLORS = {
  TEXT: {
    PRIMARY: CORE_COLORS.WHITE,
    SECONDARY: CORE_COLORS.GRAY_200,
    TERTIARY: CORE_COLORS.GRAY_600,
    ACTIVE: CORE_COLORS.GRAY_100,
    ALERT: CORE_COLORS.RED_500,
    LINK: CORE_COLORS.WMBR_GREEN,
  },
  BACKGROUND: {
    PRIMARY: CORE_COLORS.BLACK,
    SECONDARY: CORE_COLORS.GRAY_975,
    ELEVATED: CORE_COLORS.GRAY_950,
  },
  BUTTON: {
    PRIMARY: {
      BORDER: CORE_COLORS.GRAY_700,
      TEXT: CORE_COLORS.WHITE,
    },
    ACCENT: {
      BACKGROUND: CORE_COLORS.WMBR_GREEN,
      TEXT: CORE_COLORS.WHITE,
      SHADOW: CORE_COLORS.WMBR_GREEN,
    },
    ALERT: {
      BACKGROUND: CORE_COLORS.RED_500,
      TEXT: CORE_COLORS.WHITE,
    },
    SWITCH: {
      BORDER: CORE_COLORS.RED_500,
      BACKGROUND: `${CORE_COLORS.RED_500}33`,
      TEXT: CORE_COLORS.RED_500,
    },
    SWITCH_ACTIVE: {
      BORDER: CORE_COLORS.WHITE,
      BACKGROUND: CORE_COLORS.OVERLAY_WHITE_10,
      TEXT: CORE_COLORS.WHITE,
    },
  },
  INPUT: {
    BACKGROUND: CORE_COLORS.OVERLAY_WHITE_05,
    BORDER: CORE_COLORS.OVERLAY_WHITE_10,
    TEXT: CORE_COLORS.WHITE,
  },
  CARD: {
    SUBTLE: {
      BORDER: CORE_COLORS.OVERLAY_WHITE_05,
      BACKGROUND: CORE_COLORS.OVERLAY_WHITE_10,
    },
    ACTIVE: {
      BACKGROUND: `${CORE_COLORS.WMBR_GREEN}33`,
    },
  },
} as const;
