name: Build and Test - Dev

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18.20.8'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build iOS Bundle
      run: npx react-native bundle --entry-file index.ts --platform ios --dev true --bundle-output tmp/main.jsbundle

    - name: Build Android Bundle
      run: npx react-native bundle --entry-file index.ts --platform android --dev true --bundle-output android/main.jsbundle --assets-dest android
